
FIND_PATH(LIBSNDFILE_INCLUDE_DIR sndfile.h /usr/local/include /usr/include)
FIND_LIBRARY(LIBSNDFILE_LIBRARY NAMES libsndfile.a PATH /usr/local/lib /usr/lib)

IF (LIBSNDFILE_INCLUDE_DIR AND LIBSNDFILE_LIBRARY)
    SET(LIBSNDFILE_FOUND TRUE)
ENDIF (LIBSNDFILE_INCLUDE_DIR AND LIBSNDFILE_LIBRARY)

IF (LIBSNDFILE_FOUND)
    IF (NOT libsndfile_FIND_QUIETLY)
        MESSAGE(STATUS "Found libsndfile: ${LAME_INCLUDE_DIR}/sndfile.h ${LIBSNDFILE_LIBRARY}")
    ENDIF (NOT libsndfile_FIND_QUIETLY)
ELSE (LIBSNDFILE_FOUND)
    IF (libsndfile_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find libsndfile")
    ENDIF (libsndfile_FIND_REQUIRED)
ENDIF (LIBSNDFILE_FOUND)
